# Generated by Django 4.1.6 on 2023-02-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='toppping1',
            new_name='topping1',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='toppping2',
            new_name='topping2',
        ),
    ]
